Map<String, String> ar = {
  "app_name": "حجز فندق",

  "Home": "الصفحة الرئيسية",



  "press_again_to_exit": "انقر مرة اخرى للخروج",

  "menu": "القائمة",
  "home": "الرئيسية",
  "dark_mode": "الوضع الليلي",
  "language": "اللغة",
  "histories": "السجلات",
  "contact_us": "تواصل معنا",
  "color": "اللون",
  "settings": "الاعدادات",
  "our_apps": "تطبيقاتنا",

  "create": "انشاء",
  "write_barcode": "اكتب باركود",
  "barcode_format": "تنسيق الباركود",
  "format": "التنسيق",
  "search_barcode": "انشاء باركود",
  "verify_input": "يجب الا يكون هذا الحقل فارغ",


  "history": "السجل",
  "taken_from": "اخذ من",
  "input": "الادخال",
  "camera": "الكاميرا",
  "gallery": "المعرض",

  "camera_access": "الوصول الى الكاميرا يجب ان تمنح",
  "granted": "منح",
  "cancel": "الغاء",
  "there_is_not_data": "لا توجد بيانات",
  "there_is_not_flag": "لا يوجد علم",
  "error_in_db": "خطا في قاعدة البيانات",

  "scanner": "الماسح الضوئي",

  "type": "النوع",
  "product": "منتج",
  "link": "رابط",
  "normal": "عادي",
  "text": "نص",
  "numbers": "رقم",
  "normal_numbers": "رقم عادي",
  "normal_text": "نص عادي",


  "share_barcode_as_image": "مشاركة الباركود كصورة",
  "search_barcode_on_google": "البحث عن الباركود في قوقل",
  "open_link_on_browser": "فتح الرابط على متصفح الويب",
  "wiki": "ويكيبيديا",

  "saved": "تم الحفظ",
  "removed": "تم حذف",
  "save": "حفظ",
  "name": "الاسم",
  "successfully": "بنجاح",

  "height": "الطول",
  "width": "العرض",
  "size": "الحجم",
  "px": "بيكسل",
  "done": "تم",
  "barcode_height_width": "طول وعرض الباركود",

  "not_select_image": "لم تختار صورة",



  "the_inputs_is_incorrect": "المدخلات غير صحيحة",
  "height_must_between_64_and_1024": "الطول يجب ان يكون بين 64 و 1024",
  "width_must_between_64_and_1024": "العرض يجب ان يكون بين 64 و 1024",
  "size_must_between_64_and_1024": "الحجم يجب ان يكون بين 64 و 1024",
  "must_height_is_less_than_width": "يجب ان يكون الطول اقل من العرض",
  "must_width_is_more_than_height": "يجب ان يكون العرض اكبر من الطول",
  "input_is_incorrect": "المدخل غير صحيح",
  "must_height_is_not_equal_width": "يجب ان يكون الطول لا يساوي العرض",
  "must_not_contain_two_spaces_or_more_together": "يجب ألا يحتوي على مسافتين متتاليتين أو أكثر",

  "example_256": "مثال: 256",

  "country": "الدولة",
  "barcode": "الباركود",
  "unknown": "غير معروف",

  "phone": "رقم الهاتف",
  "email": "بريد الالكتروني",
  "whatsapp": "وتس اب",
  "facebook": "فيس بوك",
  "telegram": "تليقرام",
  "skip": "تخطي",
  "easy_to_find_your_distination": "وصول سريع الى وجهتكك",
  "booking_hotels": "حجز فنادق",
  "discover_place": "اكتشف اماكن جديدة",
  "life_is_only_once": "الحياة تعاش مرة واحدة",
  "enjoy_your_life": "استمتع بها",
  "sign_up": "تسجيل حساب",
  "sign_in": "تسجيل دخول",
  "or": "او",
  "login": "تسجيل الدخول",
  "forget_password": "نسيت كلمة المرور",
  "create_account": "انشاء حساب",
  "not_valid_email": "الايميل غير متوفر",
  "can't_be_empty": "لا يمكن ان يترك فارغا",
  "choose_your_favourite_distination": "اختر وجهتك المفضلة",
  "next": "التالي",
  "Okay": "حسنا",
  "selected": "مختار",
  "offers": "عروض",
  "top_rating": "أعلى التقييمات",
  "top_booking": "أعلى الحجوزات",
  "find_what_you_want": "ابحث عما تريد",
  "types": "أصناف",
  "cities": "المدن",
  "recommended_rooms" :"الغرف الموصى بها",
  "main": "الصفحة الرئيسية",
  "notification" : "الاشعارات",
  "FAQs": "الأسئلة الشائعة",
  "invite_friends": "دعوة الأصدقاء",
  "call_center": "مركز الدعم",
  "change_password": "تغيير كلمة السر",
  "logout": "تسجيل الخروج",
  "favourites": "القائمة المفضلة",
  "chat": "الدردشة",
  "hello": "مرحبا",
  "what_would_you_like_to_search": "ماذا تود البحث",
  "search": "البحث",
  "filter": "فلترة البحث",
  "price": "السعر",
  "features": "مميزات",
  "distance_from_city_center": "المسافة عن مركز المدينة",
  "type_of_accommodation": "نوع الاقامة",
  "apply": "نطبيق",
  "edit_profile": "تعديل البروفايل",
  "how_can_we_help": "كيف يمكنا المساعدة",
  "subject": "الموضوع",
  "message": "نص الرسالة",
  "send": "ارسال",
  "we_are_happy_to_help_you": "نحن سعيدون بخدمتك",
  "back": "رجوع",
  "old_password": "كلمة السر القديمة",
  "new_password": "كلمة السر الجديدة",
  "confirm_password": "تأكيد كلمة السر",
  "share": "مشاركة",
  "invite_your_friend": "دعوة صديق",
  "top_destination": "أعلى الوجهات",
  "Recommended": "موصى به",
  "hotels": "فنادق",
  "villas": "فيلات",
  "shales": "شاليهات",
  "related_rooms": "غرف مشابهة",
  "contact": "اتصال",
  "contact_info": "معلومات الاتصال",
  "about": "حول",
  "location": "الموقع",
  "reviews": "المراجعات",
  "see_all": "رؤية الكل",
  "see_contact_info": "الإطلاع على معلومات المضيف",

  "copied_successfully": "تم النسخ بنجاح",

  "update_app": "تحديث التطبيق",
  "new_version": "يتوفر إصدار جديد من التطبيق ، قم بتحديثه",
  "update": "تحديث",

  "do_you_want_to_save_the_barcode": "هل تريد حفظ الباركود؟",

  "the_internet_or_link_is_incorrect": "الإنترنت أو الرابط غير صحيح",

  "loading_rewarded_ad_please_try_again": "تحميل إعلان بمكافأة، يرجى المحاولة مرة أخرى",
  "watching": "مشاهدة",
  "watching_a_full_ad_to_printing_or_save_as_pdf": "مشاهدة إعلان كامل لطباعته أو حفظه بصيغة PDF",
  "printing_or_save_as_pdf": "الطباعة أو الحفظ بتنسيق PDF",
  "must_watch_the_ad_completely": "يجب مشاهدة الإعلان بالكامل",

};