Map<String, String> en = {
  "app_name": "TravelMate",
  "choose_the_language": "Choose the language",
  "Theres not data": "Theres not data",
  "Home": "Home page",
  "My_favorites": "My favorites",
  "Offers": "Offers",
  "Discount": "Discount",
  "user_name": "user name",
  "Ratings": "Ratings",
  "Bookings": "Bookings",
  "Types": "Types",
  "Cities": "Cities",
  "press_again_to_exit": "Press again to exit",
  "menu": "Menu",
  "home": "Home",
  "password": "password",
  "city": "city",
  "have_account": "have account",
  "dark_mode": "Dark mode",
  "language": "Language",
  "histories": "Histories",
  "contact_us": "Contact us",
  "color": "Color",
  "settings": "Settings",
  "our_apps": "Our apps",
  "create": "Create",
  "write_barcode": "Write barcode",
  "barcode_format": "Barcode format",
  "format": "Format",
  "search": "Search",
  "search_barcode": "Create a barcode",
  "verify_input": "Field must not be empty",
  "history": "History",
  "taken_from": "Taken from",
  "input": "Input",
  "camera": "Camera",
  "gallery": "Gallery",
  "camera_access": "Camera access must be granted",
  "granted": "Granted",
  "cancel": "Cancel",
  "there_is_not_data": "There is not data",
  "there_is_not_flag": "There is not flag",
  "error_in_db": "Error in database",
  "scanner": "Scanner",
  "type": "Type",
  "product": "Product",
  "link": "Link",
  "normal": "Normal",
  "text": "Text",
  "numbers": "Numbers",
  "normal_numbers": "Normal numbers",
  "normal_text": "Normal text",
  "share_barcode_as_image": "Share barcode as image",
  "search_barcode_on_google": "Search barcode on GOOGLE",
  "open_link_on_browser": "Open link on web browser",
  "wiki": "Wikipedia",
  "saved": "Saved",
  "removed": "Removed",
  "save": "Save",
  "name": "Name",
  "successfully": "Successfully",
  "height": "Height",
  "width": "Width",
  "size": "Size",
  "px": "PX",
  "done": "Done",
  "barcode_height_width": "Barcode height & width",
  "not_select_image": "Not select image",
  "the_inputs_is_incorrect": "The inputs is incorrect",
  "height_must_between_64_and_1024": "The height must between 64 and 1024",
  "width_must_between_64_and_1024": "The width must between 64 and 1024",
  "size_must_between_64_and_1024": "The size must between 64 and 1024",
  "must_height_is_less_than_width": "The Height must be less than width",
  "must_width_is_more_than_height": "The width must be greater than height",
  "input_is_incorrect": "The input is incorrect",
  "must_height_is_not_equal_width": "Must the height is not equal the width",
  "must_not_contain_two_spaces_or_more_together":
      "Must not contain two or more successive spaces",
  "example_256": "example: 256",
  "country": "Country",
  "barcode": "Barcode",
  "unknown": "Unknown",
  "phone": "Phone number",
  "email": "Email",
  "whatsapp": "Whatsapp",
  "facebook": "Facebook",
  "telegram": "Telegram",
  "skip": "Skip",
  "easy_to_find_your_distination": "Easy to find your distination",
  "booking_hotels": "Booking hotels",
  "discover_place": "Discover new places",
  "life_is_only_once": "Life is only once",
  "enjoy_your_life": "Enjoy it",
  "sign_up": "Sign up",
  "sign_in": "Sign in",
  "or": "Or",
  "login": "Login",
  "forget_password": "Forget Password",
  "create_account": "Create account",
  "not_valid_email": "Email is not valid",
  "can't_be_empty": "Can't be empty",
  "choose_your_favourite_distination": "Choose your favourite distination",
  "next": "Next",
  "Okay": "Okey",
  "selected": "selected",
  "offers": "Offers",
  "top_rating": "Top Rating",
  "top_booking": "Top Booking",
  "find_what_you_want": "Find what you want",
  "types": "Types",
  "recommended_rooms": "Recommended Rooms",
  "main": "Main",
  "notification": "Notifications",
  "FAQs": "FAQs",
  "invite_friends": "Invite frienss",
  "call_center": "Call center",
  "change_password": "Change password",
  "logout": "Logout",
  "favourites": "Favourite List",
  "chat": "Chat",
  "hello": "Hello",
  "what_would_you_like_to_search": "What would you like to search",
  "filter": "Filter",
  "price": "Price",
  "features": "Features",
  "distance_from_city_center": "Distance from city center",
  "type_of_accommodation": "Type of accommodation",
  "apply": "Apply",
  "edit_profile": "Edit profile",
  "how_can_we_help": "How can we help",
  "subject": "Subject",
  "message": "Message",
  "send": "Send",
  "we_are_happy_to_help_you": "We are happy to help you",
  "back": "back",
  "old_password": "Old password",
  "new_password": "New Password",
  "confirm_password": "Confirm password",
  "share": "Share",
  "invite_your_friend": "Invite your friends",
  "top_destination": "Top destinations",
  "Recommended": "Recommended",
  "hotels": "Hotels",
  "villas": "Villas",
  "shales": "Shalles",
  "related_rooms": "Related rooms",
  "contact": "Contact",
  "contact_info": "Contact Info",
  "about": "About",
  "location": "Location",
  "reviews": "Reviews",
  "see_all": "See all",
  "see_contact_info": "See contact info",
  "copied_successfully": "Copied successfully",
  "update_app": "Update app",
  "new_version": "A new version of the application is available, update it",
  "update": "Update",
  "do_you_want_to_save_the_barcode": "Do you want to save the barcode?",
  "the_internet_or_link_is_incorrect": "The internet or the link is incorrect",
  "loading_rewarded_ad_please_try_again":
      "Loading rewarded Ad, Please try again",
  "watching": "Watching",
  "watching_a_full_ad_to_printing_or_save_as_pdf":
      "Watching a full Ad to printing or save as Pdf",
  "printing_or_save_as_pdf": "Printing or save as Pdf",
  "must_watch_the_ad_completely": "Must watch the Ad completely",
};
